// Code generated by mockery v2.20.2. DO NOT EDIT.

package server

import (
	context "context"

	discovery "github.com/OpenBankingUK/conformance-suite/pkg/discovery"
	events "github.com/OpenBankingUK/conformance-suite/pkg/executors/events"

	executors "github.com/OpenBankingUK/conformance-suite/pkg/executors"

	generation "github.com/OpenBankingUK/conformance-suite/pkg/generation"

	manifest "github.com/OpenBankingUK/conformance-suite/pkg/manifest"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/OpenBankingUK/conformance-suite/pkg/repository"

	results "github.com/OpenBankingUK/conformance-suite/pkg/executors/results"
)

// Journey is an autogenerated mock type for the Journey type
type MockJourney struct {
	mock.Mock
}

// AllTokenCollected provides a mock function with given fields:
func (_m *MockJourney) AllTokenCollected() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CollectToken provides a mock function with given fields: code, state, scope
func (_m *MockJourney) CollectToken(code string, state string, scope string) error {
	ret := _m.Called(code, state, scope)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(code, state, scope)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConditionalProperties provides a mock function with given fields:
func (_m *MockJourney) ConditionalProperties() []discovery.ConditionalAPIProperties {
	ret := _m.Called()

	var r0 []discovery.ConditionalAPIProperties
	if rf, ok := ret.Get(0).(func() []discovery.ConditionalAPIProperties); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]discovery.ConditionalAPIProperties)
		}
	}

	return r0
}

// DiscoveryModel provides a mock function with given fields:
func (_m *MockJourney) DiscoveryModel() (discovery.Model, error) {
	ret := _m.Called()

	var r0 discovery.Model
	var r1 error
	if rf, ok := ret.Get(0).(func() (discovery.Model, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() discovery.Model); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(discovery.Model)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Events provides a mock function with given fields:
func (_m *MockJourney) Events() events.Events {
	ret := _m.Called()

	var r0 events.Events
	if rf, ok := ret.Get(0).(func() events.Events); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(events.Events)
		}
	}

	return r0
}

// FilteredManifests provides a mock function with given fields:
func (_m *MockJourney) FilteredManifests() (manifest.Scripts, error) {
	ret := _m.Called()

	var r0 manifest.Scripts
	var r1 error
	if rf, ok := ret.Get(0).(func() (manifest.Scripts, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() manifest.Scripts); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(manifest.Scripts)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: userEmail
func (_m *MockJourney) GetUserByEmail(userEmail string) (*repository.User, error) {
	ret := _m.Called(userEmail)

	var r0 *repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repository.User, error)); ok {
		return rf(userEmail)
	}
	if rf, ok := ret.Get(0).(func(string) *repository.User); ok {
		r0 = rf(userEmail)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repository.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HistoricalRunsForUser provides a mock function with given fields: ctx, userID
func (_m *MockJourney) HistoricalRunsForUser(ctx context.Context, userID string) ([]repository.TestRun, error) {
	ret := _m.Called(ctx, userID)

	var r0 []repository.TestRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]repository.TestRun, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []repository.TestRun); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.TestRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDaemonController provides a mock function with given fields:
func (_m *MockJourney) NewDaemonController() {
	_m.Called()
}

// RegisterUser provides a mock function with given fields: user
func (_m *MockJourney) RegisterUser(user repository.User) error {
	ret := _m.Called(user)

	var r0 error
	if rf, ok := ret.Get(0).(func(repository.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Results provides a mock function with given fields:
func (_m *MockJourney) Results() executors.DaemonController {
	ret := _m.Called()

	var r0 executors.DaemonController
	if rf, ok := ret.Get(0).(func() executors.DaemonController); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(executors.DaemonController)
		}
	}

	return r0
}

// RunTests provides a mock function with given fields:
func (_m *MockJourney) RunTests() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveTestCaseResult provides a mock function with given fields: result
func (_m *MockJourney) SaveTestCaseResult(result results.TestCase) error {
	ret := _m.Called(result)

	var r0 error
	if rf, ok := ret.Get(0).(func(results.TestCase) error); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetConfig provides a mock function with given fields: config
func (_m *MockJourney) SetConfig(config JourneyConfig) error {
	ret := _m.Called(config)

	var r0 error
	if rf, ok := ret.Get(0).(func(JourneyConfig) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetDiscoveryModel provides a mock function with given fields: discoveryModel
func (_m *MockJourney) SetDiscoveryModel(discoveryModel *discovery.Model) (discovery.ValidationFailures, error) {
	ret := _m.Called(discoveryModel)

	var r0 discovery.ValidationFailures
	var r1 error
	if rf, ok := ret.Get(0).(func(*discovery.Model) (discovery.ValidationFailures, error)); ok {
		return rf(discoveryModel)
	}
	if rf, ok := ret.Get(0).(func(*discovery.Model) discovery.ValidationFailures); ok {
		r0 = rf(discoveryModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(discovery.ValidationFailures)
		}
	}

	if rf, ok := ret.Get(1).(func(*discovery.Model) error); ok {
		r1 = rf(discoveryModel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetFilteredManifests provides a mock function with given fields: _a0
func (_m *MockJourney) SetFilteredManifests(_a0 manifest.Scripts) {
	_m.Called(_a0)
}

// StopTestRun provides a mock function with given fields:
func (_m *MockJourney) StopTestRun() {
	_m.Called()
}

// TLSVersionResult provides a mock function with given fields:
func (_m *MockJourney) TLSVersionResult() map[string]*discovery.TLSValidationResult {
	ret := _m.Called()

	var r0 map[string]*discovery.TLSValidationResult
	if rf, ok := ret.Get(0).(func() map[string]*discovery.TLSValidationResult); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*discovery.TLSValidationResult)
		}
	}

	return r0
}

// TestCases provides a mock function with given fields: userID
func (_m *MockJourney) TestCases(userID string) (generation.SpecRun, error) {
	ret := _m.Called(userID)

	var r0 generation.SpecRun
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (generation.SpecRun, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) generation.SpecRun); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(generation.SpecRun)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewJourney interface {
	mock.TestingT
	Cleanup(func())
}

// NewJourney creates a new instance of Journey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockJourney(t mockConstructorTestingTNewJourney) *MockJourney {
	mock := &MockJourney{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
