// Code generated by mockery v1.0.0. DO NOT EDIT.

package generation

import discovery "bitbucket.org/openbankingteam/conformance-suite/pkg/discovery"
import logrus "github.com/sirupsen/logrus"
import mock "github.com/stretchr/testify/mock"
import model "bitbucket.org/openbankingteam/conformance-suite/pkg/model"

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

// GenerateSpecificationTestCases provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockGenerator) GenerateSpecificationTestCases(_a0 *logrus.Entry, _a1 GeneratorConfig, _a2 discovery.ModelDiscovery, _a3 *model.Context) TestCasesRun {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 TestCasesRun
	if rf, ok := ret.Get(0).(func(*logrus.Entry, GeneratorConfig, discovery.ModelDiscovery, *model.Context) TestCasesRun); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(TestCasesRun)
	}

	return r0
}
