// Code generated by mockery v1.0.0. DO NOT EDIT.

package generation

import discovery "bitbucket.org/openbankingteam/conformance-suite/pkg/discovery"
import mock "github.com/stretchr/testify/mock"
import model "bitbucket.org/openbankingteam/conformance-suite/pkg/model"

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

// GenerateSpecificationTestCases provides a mock function with given fields: config, _a1, ctx
func (_m *MockGenerator) GenerateSpecificationTestCases(config GeneratorConfig, _a1 discovery.ModelDiscovery, ctx *model.Context) TestCasesRun {
	ret := _m.Called(config, _a1, ctx)

	var r0 TestCasesRun
	if rf, ok := ret.Get(0).(func(GeneratorConfig, discovery.ModelDiscovery, *model.Context) TestCasesRun); ok {
		r0 = rf(config, _a1, ctx)
	} else {
		r0 = ret.Get(0).(TestCasesRun)
	}

	return r0
}
