// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import rsa "crypto/rsa"
import tls "crypto/tls"

// Certificate is an autogenerated mock type for the Certificate type
type Certificate struct {
	mock.Mock
}

// PrivateKey provides a mock function with given fields:
func (_m *Certificate) PrivateKey() *rsa.PrivateKey {
	ret := _m.Called()

	var r0 *rsa.PrivateKey
	if rf, ok := ret.Get(0).(func() *rsa.PrivateKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PrivateKey)
		}
	}

	return r0
}

// PublicKey provides a mock function with given fields:
func (_m *Certificate) PublicKey() *rsa.PublicKey {
	ret := _m.Called()

	var r0 *rsa.PublicKey
	if rf, ok := ret.Get(0).(func() *rsa.PublicKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PublicKey)
		}
	}

	return r0
}

// TLSCert provides a mock function with given fields:
func (_m *Certificate) TLSCert() tls.Certificate {
	ret := _m.Called()

	var r0 tls.Certificate
	if rf, ok := ret.Get(0).(func() tls.Certificate); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(tls.Certificate)
	}

	return r0
}
