// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import discovery "bitbucket.org/openbankingteam/conformance-suite/pkg/discovery"
import generation "bitbucket.org/openbankingteam/conformance-suite/pkg/generation"
import mock "github.com/stretchr/testify/mock"
import model "bitbucket.org/openbankingteam/conformance-suite/pkg/model"

// Generator is an autogenerated mock type for the Generator type
type Generator struct {
	mock.Mock
}

// GenerateSpecificationTestCases provides a mock function with given fields: _a0, _a1, _a2
func (_m *Generator) GenerateSpecificationTestCases(_a0 generation.GeneratorConfig, _a1 discovery.ModelDiscovery, _a2 *model.Context) generation.TestCasesRun {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 generation.TestCasesRun
	if rf, ok := ret.Get(0).(func(generation.GeneratorConfig, discovery.ModelDiscovery, *model.Context) generation.TestCasesRun); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(generation.TestCasesRun)
	}

	return r0
}
