#!/usr/bin/env bash

if ! command -v docker &> /dev/null
then
	echo 'Docker is required for this script. Please install it at https://docs.docker.com/get-docker/';
	exit 1
fi;

DB_USER=postgres
DB_PASS=passw0rd
DB_NAME=postgres
DB_PORT=7312
CONTAINER_NAME=conformance-suite

echo 'Making sure database name is available...';

docker rm -f conformance-suite

echo 'Starting database...';

docker run --name conformance-suite --rm -e POSTGRES_USER="${DB_USER}" -e POSTGRES_DB="${DB_NAME}" -e POSTGRES_PASSWORD="${DB_PASS}" -p "0.0.0.0:${DB_PORT}:5432" -d postgres

echo 'Waiting for database to be ready...';

sleep 10

echo 'Done';