#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${SCRIPT_DIR}/.."

echo -e '\033[92m  ---> Starting server ... \033[0m'
go run cmd/server/main.go
