#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "${SCRIPT_DIR}/.."

echo -e '\033[92m  ---> Starting web file watcher ... \033[0m'
cd web && \
    FORCE_COLOR=1 NODE_DISABLE_COLORS=0 yarn install --frozen-lockfile --non-interactive && \
    FORCE_COLOR=1 NODE_DISABLE_COLORS=0 yarn build-watch
