// Code generated by mockery v1.0.0. DO NOT EDIT.

package main

import io "io"
import mock "github.com/stretchr/testify/mock"
import server "bitbucket.org/openbankingteam/conformance-suite/pkg/server"

// MockGenerator is an autogenerated mock type for the Generator type
type MockGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: config, input, output
func (_m *MockGenerator) Generate(config server.JourneyConfig, input io.Reader, output io.Writer) error {
	ret := _m.Called(config, input, output)

	var r0 error
	if rf, ok := ret.Get(0).(func(server.JourneyConfig, io.Reader, io.Writer) error); ok {
		r0 = rf(config, input, output)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
