export const SET_CONFIG = 'SET_CONFIG';
export const SET_DISCOVERY_MODEL = 'SET_DISCOVERY_MODEL';
export const DISCOVERY_MODEL_PROBLEMS = 'DISCOVERY_MODEL_PROBLEMS';

export const SET_CONFIGURATION_SIGNING_PRIVATE = 'SET_CONFIGURATION_SIGNING_PRIVATE';
export const SET_CONFIGURATION_SIGNING_PUBLIC = 'SET_CONFIGURATION_SIGNING_PUBLIC';
export const SET_CONFIGURATION_TRANSPORT_PRIVATE = 'SET_CONFIGURATION_TRANSPORT_PRIVATE';
export const SET_CONFIGURATION_TRANSPORT_PUBLIC = 'SET_CONFIGURATION_TRANSPORT_PUBLIC';
export const SET_CONFIGURATION_ERRORS = 'SET_CONFIGURATION_ERRORS';
export const ADD_CONFIGURATION_ERRORS = 'ADD_CONFIGURATION_ERRORS';
export const CLEAR_CONFIGURATION_ERRORS = 'CLEAR_CONFIGURATION_ERRORS';
