export const SET_DISCOVERY_MODEL = 'SET_DISCOVERY_MODEL';
export const DISCOVERY_MODEL_PROBLEMS = 'DISCOVERY_MODEL_PROBLEMS';

export const SET_CONFIGURATION = 'SET_CONFIGURATION';
export const SET_CONFIGURATION_SIGNING_PRIVATE = 'SET_CONFIGURATION_SIGNING_PRIVATE';
export const SET_CONFIGURATION_SIGNING_PUBLIC = 'SET_CONFIGURATION_SIGNING_PUBLIC';
export const SET_CONFIGURATION_TRANSPORT_PRIVATE = 'SET_CONFIGURATION_TRANSPORT_PRIVATE';
export const SET_CONFIGURATION_TRANSPORT_PUBLIC = 'SET_CONFIGURATION_TRANSPORT_PUBLIC';
export const SET_DISCOVERY_TEMPLATES = 'SET_DISCOVERY_TEMPLATES';

export const SET_WIZARD_STEP = 'SET_WIZARD_STEP';

export const SET_CLIENT_ID = 'SET_CLIENT_ID';
export const SET_CLIENT_SECRET = 'SET_CLIENT_SECRET';
export const SET_TOKEN_ENDPOINT = 'SET_TOKEN_ENDPOINT';
export const SET_TOKEN_ENDPOINT_AUTH_METHOD = 'SET_TOKEN_ENDPOINT_AUTH_METHOD';
export const SET_TOKEN_ENDPOINT_AUTH_METHODS = 'SET_TOKEN_ENDPOINT_AUTH_METHODS';
export const SET_AUTHORIZATION_ENDPOINT = 'SET_AUTHORIZATION_ENDPOINT';
export const SET_RESOURCE_BASE_URL = 'SET_RESOURCE_BASE_URL';
export const SET_X_FAPI_FINANCIAL_ID = 'SET_X_FAPI_FINANCIAL_ID';
export const SET_ISSUER = 'SET_ISSUER';
export const SET_REDIRECT_URL = 'SET_REDIRECT_URL';
export const SET_RESOURCE_ACCOUNT_ID = 'SET_RESOURCE_ACCOUNT_ID';
export const SET_RESOURCE_STATEMENT_ID = 'SET_RESOURCE_STATEMENT_ID';
export const SET_RESOURCE_ACCOUNT_IDS = 'SET_RESOURCE_ACCOUNT_IDS';
export const SET_RESOURCE_STATEMENT_IDS = 'SET_RESOURCE_STATEMENT_IDS';
export const ADD_RESOURCE_ACCOUNT_ID = 'ADD_RESOURCE_ACCOUNT_ID';
export const REMOVE_RESOURCE_ACCOUNT_ID = 'REMOVE_RESOURCE_ACCOUNT_ID';
export const ADD_RESOURCE_STATEMENT_ID = 'ADD_RESOURCE_STATEMENT_ID';
export const REMOVE_RESOURCE_STATEMENT_ID = 'REMOVE_RESOURCE_STATEMENT_ID';
