export const SET_CONFIG = 'SET_CONFIG';
export const SET_DISCOVERY_MODEL = 'SET_DISCOVERY_MODEL';
export const UPDATE_DISCOVERY_MODEL = 'UPDATE_DISCOVERY_MODEL';
export const DELETE_DISCOVERY_MODEL = 'DELETE_DISCOVERY_MODEL';
